accessLogsFile = "/dev/stdout"
defaultEntryPoints = ["https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/run/secrets/cert.pem"
      KeyFile = "/run/secrets/key.pem"

[web]
address = ":8080"
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domain.local"
watch = true
swarmmode = true
exposedbydefault = false

#[acme]
#email = "verbruggenalex@gmail.com"
#storage = "/tmp/acme.json"
#entryPoint = "https"
#onDemand = true
#onHostRule = false
#caServer = "https://acme-staging.api.letsencrypt.org/directory"
#  [acme.httpChallenge]
#  entryPoint="http"
#[[acme.domains]]
#  main = "domain.local"
#  sans = ["traefik.domain.local", "cloud9.domain.local"]
